### ISSUE TITLE
Add a way to merge user provided handlers with bind handlers

### ISSUE THREAD

**Issue by slorber** [sandiiarov/use-events#113]
Even if this lib binds the focus, we still may want to listen for focus events from outside

```js
  const [isFocused, bindFocus] = useFocus();


    <AppInputText
      {...inputTextProps}
      onFocus={e => {
        bindFocus.onFocus(e);
        inputTextProps.onFocus && inputTextProps.onFocus(e);
      }}
      onBlur={e => {
        bindFocus.onBlur(e);
        inputTextProps.onBlur && inputTextProps.onBlur(e);
      }}
    />
```

I'd like to be able to write something simpler like

```js
  const [isFocused, bindFocus] = useFocus(inputTextProps);

    <AppInputText
      {...inputTextProps}
      {...bindFocus}
    />
```

I can already simplify this with something like that. Could serve for other users if this was in the lib. (just remove null handlers and call all handlers in the list)

```js
  const [isFocused, bindFocus] = useFocus();


    <AppInputText
      {...inputTextProps}
      onFocus={e => mergeHandlers([bindFocus.onFocus,inputTextProps.onFocus])}
      onBlur={e => mergeHandlers([bindFocus.onBlur,inputTextProps.onBlur])}
    />
```

When multiple handlers can be provided it's easy to have the outside handler override the bind handler or vice versa. 

This could apply to other hooks as well.

**Comment by therealparmesh** [comment]
What about doing something like [copying `callAll` from `react-toggled`](https://github.com/kentcdodds/react-toggled/blob/8452a1f2a4ec7b64588cd8c9812e0faf8deb0271/src/index.js#L4)?

Then you could write:
```jsx
const Example = ({ onFocus, onBlur }) => {
  const [isFocused, bind] = useFocus();

  return (
    <div>
      <input onFocus={callAll(bind.onFocus, onFocus)} onBlur={callAll(bind.onBlur, onBlur)}  placeholder="Focus me" />
      <div>You are {isFocused ? 'focusing' : 'not focusing'} the input</div>
    </div>
  );
};
```

**Comment by slorber** [comment]
Yes basically merge Handler is callAll

**Comment by therealparmesh** [comment]
Yup!

**Comment by sandiiarov** [comment]
@slorber Feel free to create a PR with `callAll` utils function. I would be happy to merge it.
