### ISSUE TITLE
1.4.0 build can no longer be imported by webpack

### ISSUE THREAD

**Issue by martinbroos** [sandiiarov/use-events#188]
When i'm looking at your changes I see you made the change to use pika as your bundler. I'm not familiar with and now i'm not sure how to use the package. This fails with webpack:

`import { useMousePosition } from 'use-events';`

Do I need @pika/web in my application now or is their another way to get it working with webpack? When i'm importing the src file directly I'm getting a loader error as my webpack config can not handle esm modules I guess.

**Comment by flowen** [comment]
same error in gatsby

**Comment by sandiiarov** [comment]
Should work in 1.4.1

**Comment by martinbroos** [comment]
Tested and works again 👍
