### ISSUE TITLE
Bug related to wrong use of useEffect. Callback is not gets updated.

### ISSUE THREAD

**Issue by RIP21** [sandiiarov/use-events#35]
The bug is extremely weird and I'm not sure whether it's `useClickOutside` broken or React.
Reproduce CodeSandox is here: https://codesandbox.io/s/lr668rr94m

Long story short. I want to handle some logic only when something is `inProgress` if it's not in progress no state changes should happen.
But when this actual thing is indeed `inProgress` (has a `true` value) in `render` scope it's actually `true` while in callback it somehow appears to be still `false`. 
I assume there is some `useCallback` issues involved and rather in `use-events` than in React :) So please address those :)

**Comment by RIP21** [comment]
Just checked source code of `useClickOutside` and there is no `useCallback` involved.
So, I assume, it's a bug of React. Will report it there with reference.

**Comment by RIP21** [comment]
Ok... I think I fixed it removing `[]` from `useEffect`. Can somebody explain to me, what does that change at all?

**Comment by RIP21** [comment]
Found what is the issue. Don't know how to effectively fix it yet, but it's not a React issue.

**Comment by RIP21** [comment]
Gotcha, omitting it, causing it to rerun `useEffects` every rerender. Hence callback function is getting updated, hence behavior is as expected. Before, with only `[]` it was using the first version of the callback and all new versions of callback are ignored.

**Comment by RIP21** [comment]
https://github.com/Andarist/use-onclickoutside/blob/master/src/index.ts
Steal something from it :D

**Comment by sandiiarov** [comment]
@RIP21 Thanks for digging into this!

I'll take a deeper look as well later today.

**Comment by sandiiarov** [comment]
@RIP21 Fix in v1.1.11. Feel free to re-open this issue if it is not helpful.
