### ISSUE TITLE
The plan about use-events library

### ISSUE THREAD

**Issue by WJWang** [sandiiarov/use-events#59]
Hi @sandiiarov,  I think use-events will be very useful as a react hook utility library.  Just curious about your plan about this repository. Will you plan to include more events hook in the repo ? If so, what events will be on your pending list.

**Comment by sandiiarov** [comment]
To be honest I don't have a roadmap. I just wanted to add [useResizeObserver](https://github.com/sandiiarov/use-events/pull/60) because I don't like other solutions.

Do you want to add something else?

**Comment by WJWang** [comment]
I have no idea for whole roadmap either. But, I think on scroll event can be added.

**Comment by sandiiarov** [comment]
Hmm. That is interesting idea. Do you want to do that?

**Comment by WJWang** [comment]
Sure, I can do it.

**Comment by WJWang** [comment]
I have added useScroll in #65
